[unix_http_server]
file=/run/novelpia/supervisor.sock
chmod=0700

[supervisord]
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/novelpia/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/novelpia/supervisor.sock

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1200x800x24 -nolisten tcp -ac
user=novelpia
priority=10
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:app]
command=/opt/service/start-app.sh
user=novelpia
environment=HOME="/home/novelpia"
priority=30
autorestart=true
stopsignal=TERM
stopwaitsecs=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=60
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
